version: "3.7"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh
    command: sleep infinity
    user: 1000:1000
    networks:
      - default

  redis:
    image: redis
    command: [ "sh", "-c", "exec redis-server" ]
    ports:
      - "6379:6379"
    networks:
      - default

  gateway:
    restart: unless-stopped
    build:
      context: ../gateway
      dockerfile: Dockerfile
    environment:
      DOLLAR: "$$"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - 80:80
    networks:
      - default

  listener:
    restart: always
    depends_on:
      - redis
    build:
      context: ../listener
      dockerfile: Dockerfile
    command: [ "sh", "-c", "nodemon main.js" ]
    volumes:
      - ../listener:/app
    env_file: ../listener/.env
    networks:
      - default

  worker:
    restart: unless-stopped
    user: 1000:1000
    build:
      context: ../worker
      dockerfile: Dockerfile
    command:
      - "./scripts/entrypoint.dev.sh"
    volumes:
      - ../worker:/app
    ports:
      - "3000:3000"
    networks:
      - default
    #env_file: devcontainer.env
    depends_on:
      - redis
      - listener

networks:
  default:
    driver: bridge
